//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falabella.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FalabellaEntities : DbContext
    {
        public FalabellaEntities()
            : base("name=FalabellaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fal_Dic_Cliente> Fal_Dic_Cliente { get; set; }
        public virtual DbSet<Fal_Dic_Compania> Fal_Dic_Compania { get; set; }
        public virtual DbSet<Fal_Dic_Producto> Fal_Dic_Producto { get; set; }
        public virtual DbSet<Fal_Dic_TipoDocumento> Fal_Dic_TipoDocumento { get; set; }
        public virtual DbSet<Fal_Dic_Usuario> Fal_Dic_Usuario { get; set; }
        public virtual DbSet<Fal_DicPerfil> Fal_DicPerfil { get; set; }
        public virtual DbSet<Fal_Tra_CompaniaProducto> Fal_Tra_CompaniaProducto { get; set; }
        public virtual DbSet<Fal_Tra_Venta> Fal_Tra_Venta { get; set; }
    }
}
