//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falabella.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fal_Tra_CompaniaProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fal_Tra_CompaniaProducto()
        {
            this.Fal_Tra_Venta = new HashSet<Fal_Tra_Venta>();
        }
    
        public int cop_IdCompaniaProducto_PK { get; set; }
        public int cop_IdCompania_FK { get; set; }
        public int cop_IdProducto_FK { get; set; }
        public int cop_IdUsuario_FK { get; set; }
        public bool cop_Estado { get; set; }
        public System.DateTime cop_FechaRegistro { get; set; }
    
        public virtual Fal_Dic_Compania Fal_Dic_Compania { get; set; }
        public virtual Fal_Dic_Producto Fal_Dic_Producto { get; set; }
        public virtual Fal_Dic_Usuario Fal_Dic_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fal_Tra_Venta> Fal_Tra_Venta { get; set; }
    }
}
