//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falabella.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fal_DicPerfil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fal_DicPerfil()
        {
            this.Fal_Dic_Usuario = new HashSet<Fal_Dic_Usuario>();
        }
    
        public int per_IdPerfil_PK { get; set; }
        public string per_Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fal_Dic_Usuario> Fal_Dic_Usuario { get; set; }
    }
}
