//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falabella.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fal_Dic_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fal_Dic_Usuario()
        {
            this.Fal_Dic_Cliente = new HashSet<Fal_Dic_Cliente>();
            this.Fal_Dic_Compania = new HashSet<Fal_Dic_Compania>();
            this.Fal_Dic_Producto = new HashSet<Fal_Dic_Producto>();
            this.Fal_Tra_CompaniaProducto = new HashSet<Fal_Tra_CompaniaProducto>();
            this.Fal_Tra_Venta = new HashSet<Fal_Tra_Venta>();
        }
    
        public int usu_IdUsuario_PK { get; set; }
        public int usu_IdPerfil_FK { get; set; }
        public string usu_Nombre { get; set; }
        public string usu_Usuario { get; set; }
        public System.DateTime usu_FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fal_Dic_Cliente> Fal_Dic_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fal_Dic_Compania> Fal_Dic_Compania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fal_Dic_Producto> Fal_Dic_Producto { get; set; }
        public virtual Fal_DicPerfil Fal_DicPerfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fal_Tra_CompaniaProducto> Fal_Tra_CompaniaProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fal_Tra_Venta> Fal_Tra_Venta { get; set; }
    }
}
