//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falabella.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fal_Tra_Venta
    {
        public int ven_IdVenta_PK { get; set; }
        public int ven_IdCompaniaProducto_FK { get; set; }
        public int ven_IdCliente_FK { get; set; }
        public int ven_IdUsuario_FK { get; set; }
        public Nullable<int> ven_Cantidad { get; set; }
        public Nullable<int> ven_Valor { get; set; }
        public string ven_Observacion { get; set; }
        public System.DateTime ven_FechaRegistro { get; set; }
    
        public virtual Fal_Dic_Cliente Fal_Dic_Cliente { get; set; }
        public virtual Fal_Dic_Usuario Fal_Dic_Usuario { get; set; }
        public virtual Fal_Tra_CompaniaProducto Fal_Tra_CompaniaProducto { get; set; }
    }
}
