//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falabella.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fal_Dic_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fal_Dic_Cliente()
        {
            this.Fal_Tra_Venta = new HashSet<Fal_Tra_Venta>();
        }
    
        public int cli_IdCliente_PK { get; set; }
        public int cli_IdUsuario_FK { get; set; }
        public int cli_IdTipoDocumento_FK { get; set; }
        public string cli_Nombre { get; set; }
        public string cli_Documento { get; set; }
        public Nullable<System.DateTime> cli_FechaNacimiento { get; set; }
        public System.DateTime cli_FechaRegistro { get; set; }
    
        public virtual Fal_Dic_TipoDocumento Fal_Dic_TipoDocumento { get; set; }
        public virtual Fal_Dic_Usuario Fal_Dic_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fal_Tra_Venta> Fal_Tra_Venta { get; set; }
    }
}
